CREATE DATABASE comercio;

USE COMERCIO;

CREATE TABLE PRODUCTO (
ID INT PRIMARY KEY AUTO INCREMENT NOT NULL,
nombre VARCHAR(120) NOT NULL,
codigo VARCHAR (120) NOT NULL,
stock INT NOT NULL,
precio_compra DECIMAL (10,2) NOT NULL,
precio_venta DECIMAL(10,2) NOT NULL,
id_categoria INT NOT NULL,
created_user INT NOT NULL,
update_user INT NOT NULL
);